### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by dedu6ka** [jeffreymb/anki-flip-card-order#3]
I clicked on the "Flip card order" for the first time - got this:  

Traceback (most recent call last):
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.webview", line 21, in link
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.hooks", line 61, in repl
  File "C:\Users\Vit\Documents\Anki\addons\Flip_BASIC_NOTE_Card_Order.py", line 36, in linkHandler
    flipCardOrder(self)
  File "C:\Users\Vit\Documents\Anki\addons\Flip_BASIC_NOTE_Card_Order.py", line 46, in flipCardOrder
    otherCard = getOtherCard(self, curCard)
  File "C:\Users\Vit\Documents\Anki\addons\Flip_BASIC_NOTE_Card_Order.py", line 91, in getOtherCard
    otherId = [c.id for c in note.cards() if c.id != curId][0]
IndexError: list index out of range  

Also would be helpful to rename it 'Flip Basic Card".  
Thank you

**Comment by jeffreymb** [comment]
1. Why would it be helpful to rename the Add On? Changing it to "basic note" probably isn't what I would do as it works with any note type that has only two cards.

2. Has the issue continued beyond the first time you tried it? Or was this a single event?

I'm not likely to have time for a fix in the near future so if you have the skill to submit a Pull Request that would be great!

**Comment by dedu6ka** [comment]
I have thought we are flipping 'Fields', permanently, because doing it temporarily, for each card,  makes no sense to ME.  I was going to convert a selected BASIC Passive card ( after 5-7 reps) to Active card while in the 'Show answer" screen.  
Can you do that please ?

PS.It works on Basic and reverse note. but i do not need this option :-(    When i needed to reverse the cards order, i changed ALL notes at once by changing the Note Type.

Thank you for responding.



--------------------------------------------
On Thu, 11/24/16, Jeffrey Brubaker <notifications@github.com> wrote:

 Subject: Re: [jeffreymb/anki-flip-card-order] Error Message (#3)
 To: "jeffreymb/anki-flip-card-order" <anki-flip-card-order@noreply.github.com>
 Cc: "dedu6ka" <vrem2003-temporary@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Thursday, November 24, 2016, 8:17 AM
  
 Has the issue continued beyond the first time you tried
 it? Or was this a single event?
 
 
 I'm not likely to have time for a fix in the near
 future so if you have the skill to submit a Pull Request
 that would be great!
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by jeffreymb** [comment]
I don't think the functionality of this plug in what you are looking for. This does not flip fields, but rather flips the order of cards in notes with two cards. Furthermore, it only works when on the first review. After you've seen both cards in the note, the option to flip the order with this add on is no longer available.
